prod-devel-rcar.yaml: Set I_SWEAR_TO_MIGRATE_TO_PYTHON3 to yes
In order to make gles-um-compile.bb happy, which still requires it.
This temp solution is suggested by error message below (trimmed a bit).

ERROR: Nothing RPROVIDES 'python' (but ../gles-um-compile.bb RDEPENDS on or otherwise requires it)
python was skipped: Recipe will be skipped because: python2 is out of support for long time,
read https://www.python.org/doc/sunset-python-2/ https://python3statement.org/
and if you really have to temporarily use this, then set I_SWEAR_TO_MIGRATE_TO_PYTHON3 to "yes"

Signed-off-by: Oleksandr Tyshchenko <oleksandr_tyshchenko@epam.com>