prod-devel-rcar.yaml: Remove strace from the build
It is causing a build error after switching to the new Renesas BSP
5.9.0 and Yocto Kirkstone:

../strace-5.10/v4l2.c:23:9: error: static assertion failed:
"Unexpected struct v4l2_create_buffers.reserved size, please
update the decoder"

If we will need this tool, we will investigate this issue later on.

Signed-off-by: Vladyslav Goncharuk <vladyslav_goncharuk@epam.com>